apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: ctorres
  labels:
    app: crud
spec:
  storageClassName: storage-crud
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/crud-data"